---
roles:
  - name: cloudalchemy.node-exporter
    version: 0.19.0
  - name: kwoodson.yedit
# pull from GitHub to ensure up-to-date version
  - name: n0emis.bigbluebutton
    src: https://github.com/n0emis/ansible-role-bigbluebutton
    version: master
  - name: geerlingguy.nodejs
    version: 5.1.1
  - name: geerlingguy.redis
    version: 1.6.0
  - name: geerlingguy.postgresql
    version: 2.2.0
  - name: geerlingguy.ruby
    version: 2.6.0
  - name: cloudalchemy.prometheus
    version: 2.15.0
  - name: cloudalchemy.grafana
    version: 0.17.0