---
- name: ensure we're using mp4 for recordings
  yedit:
    src: /usr/local/bigbluebutton/core/scripts/presentation.yml
    key: video_formats
    value:
      - mp4
  notify: restart bigbluebutton

- name: ensure default recording is enabled
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: "^disableRecordingDefault="
    line: "disableRecordingDefault=false"
  notify: restart bigbluebutton
  when: recording_server|bool

- name: ensure default recording is enabled
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: "^disableRecordingDefault="
    line: "disableRecordingDefault=true"
  notify: restart bigbluebutton
  when: not recording_server|bool

- name: ensure recording auto start is disabled
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: "^autoStartRecording="
    line: "autoStartRecording=false"
  notify: restart bigbluebutton

- name: ensure users are allowed to start recording
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: "^allowStartStopRecording="
    line: "allowStartStopRecording=true"
  notify: restart bigbluebutton
  when: recording_server|bool

- name: ensure users are allowed to start recording
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: "^allowStartStopRecording="
    line: "allowStartStopRecording=false"
  notify: restart bigbluebutton
  when: not recording_server|bool

- name: customize welcome meeting header
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: "^defaultWelcomeMessage="
    line: "defaultWelcomeMessage=Welcome to <b>%%CONFNAME%%</b>!<br><br>For help on using BigBlueButton see these (short) <a href=\"event:http://www.bigbluebutton.org/html5\"><u>tutorial videos</u></a>.<br><br>To join the audio bridge click the phone button. Use a headset to avoid causing background noise for others."
  notify: restart bigbluebutton

- name: enforce meeting duration limit
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: "^defaultMeetingDuration="
    line: "defaultMeetingDuration=480"
  notify: restart bigbluebutton

- name: customize welcome meeting footer
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: "^defaultWelcomeMessageFooter="
    line: "defaultWelcomeMessageFooter=Please report all queries and issues to support@srcf.net."
  notify: restart bigbluebutton

- name: ensure that our favicon is used
  copy:
    src: favicon.ico
    dest: /var/www/bigbluebutton-default/favicon.ico

- name: ensure http call to root is redirected
  copy:
    content: |
      location = / {
        return 301 https://timeout.srcf.net;
      }
    mode: 0755
    dest: /etc/bigbluebutton/nginx/redirectroot.nginx
  notify: reload nginx

- name: ensure our own default slides are used
  copy:
    src: default.pdf
    dest: /var/www/bigbluebutton-default/default.pdf

- name: copy our own mute/unmute sounds
  copy:
    src: "{{ item }}"
    dest: "/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/{{item}}"
  with_items:
    - conf-muted-ulmlernt.wav
    - conf-unmuted-ulmlernt.wav

- name: ensure our own mute sound is used
  xml:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
    xpath: '/configuration/profiles/profile[@name="cdquality"]/param[@name="muted-sound"]'
    attribute: value
    value: conference/conf-muted-ulmlernt.wav
  notify: restart bigbluebutton

- name: ensure our own unmute sound is used
  xml:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
    xpath: '/configuration/profiles/profile[@name="cdquality"]/param[@name="unmuted-sound"]'
    attribute: value
    value: conference/conf-unmuted-ulmlernt.wav
  notify: restart bigbluebutton

- name: ensure that alone sound is absent
  xml:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
    xpath: '/configuration/profiles/profile[@name="cdquality"]/param[@name="alone-sound"]'
    state: absent
  notify: restart bigbluebutton

- name: adapt coturn ports in ufw
  copy:
    content: |
      [turnserver]
      title=Coturn turnserver
      description=Free open source implementation of TURN and STUN Server
      ports=3478,3479,5349,5350/tcp|3478,3479,5349,5350,49152:65535/udp
    mode: 0644
    dest: /etc/ufw/applications.d/turnserver

- name: allow turnserver in ufw
  ufw:
    rule: allow
    name: turnserver
    state: enabled

- name: adapt freeswitch ports in ufw
  copy:
    content: |
      [freeswitch]
      title=freeswitch
      description=freeswitch telecom stack
      ports=16384:32768/udp
    mode: 0644
    dest: /etc/ufw/applications.d/freeswitch

- name: allow freeswitch in ufw
  ufw:
    rule: allow
    name: freeswitch
    state: enabled

- name: Ensure coturn is restarted everyday @ 4 am
  cron:
    name: "restart coturn"
    minute: "0"
    hour: "4"
    user: root
    job: "systemctl restart coturn.service"

- name: Ensure that recording archiving is enabled
  systemd:
    name: bbb-record-core.timer
    enabled: yes
    masked: no
    state: started


# needs to be removed in a future version
- name: Ensure recording processing is present
  lineinfile:
    dest: /usr/lib/systemd/system/bbb-record-core.target
    regexp: "^Wants="
    line: "Wants=bbb-rap-archive-worker.service bbb-rap-sanity-worker.service bbb-rap-process-worker.service bbb-rap-publish-worker.service bbb-rap-events-worker.service"
    state: present
  notify: reload systemd

- name: Ensure that recording processing is disabled
  systemd:
    name: bbb-rap-process-worker.service
    enabled: no
    masked: yes
    state: stopped

- name: Ensure that recording publishing is disabled
  systemd:
    name: bbb-rap-publish-worker.service
    enabled: no
    masked: yes
    state: stopped
